name: Torrent Download

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the version of Node.js you want to use

      - name: Install torrent-dl
        run: |
          npm install -g torrent-dl

      - name: Torrent Download
        env:
          TORRENT_CREDENTIALS: ${{ secrets.TORRENT_CREDENTIALS }} # Optional, if needed for authentication
        run: |
          # Create a directory to store the downloads
          mkdir -p downloads
          
          # Use torrent-dl to download the specified torrent
          torrent-dl -i "magnet:?xt=urn:btih:D0677B1288357ED570C83F61A23E4DC4D8777E81&dn=The Thin Man (1934)&tr=udp://open.demonii.com:1337/announce&tr=udp://tracker.openbittorrent.com:80&tr=udp://tracker.coppersurfer.tk:6969&tr=udp://glotorrents.pw:6969/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://torrent.gresille.org:80/announce&tr=udp://p4p.arenabg.com:1337&tr=udp://tracker.leechers-paradise.org:6969"
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: downloaded-torrent-files
          path: downloads/
